#Application properties
server:
  port: ${APP_PORT:8080}

cloud:
  endpoint: ${S3_ENDPOINT}
  region: 
    static: ${S3_REGION}
  credentials:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}

application:
  bucket:
    name: ${S3_BUCKET}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 256KB
        