#Application properties
server:
  port: 8081

#AWS properties
cloud:
  aws:
    region:
      static: sa-east-1
    stack:
      auto: false
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

application:
  bucket:
    name: modelo21

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error