#Application properties
server:
  port: ${APP_PORT:8080}

#AWS properties
cloud:
  aws:
    region:
      static: ${S3_REGION:sa-east-1}
    stack:
      auto: false
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

application:
  bucket:
    name: ${S3_BUCKET:modelo21}

